---
- name: Install tools
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - git
    - glances
    - htop
    - curl
    - rsync
  become: yes

- name: set timezone to Europe/Paris
  timezone:
    name: Europe/Paris
  become: yes

- name: restart cron service
  service:
    name: cron
    state: restarted
  become: yes