---
- name: Install packages to allow apt to use a repository over HTTPS
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates 
    - curl 
    - software-properties-common
  become: yes

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  become: yes

- name: Set up the stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  become: yes

- name: Install docke-ce
  apt: name=docker-ce state=installed update_cache=yes
  become: yes

- name: Run hello-world container
  docker_container:
    name: hello-world
    image: hello-world
    state: started
  register: result
  become: yes

- fail:
    msg: "There is a problem with docker"
  when: result|failed