# vim: set filetype=yaml expandtab tabstop=2 shiftwidth=2 softtabstop=2 background=dark :

- name: create virtual IP resource
  shell: pcs resource create "{{ postgres_ha_cluster_vip_res_name }}" ocf:heartbeat:IPaddr2 ip="{{ postgres_ha_cluster_vip }}" cidr_netmask="{{ postgres_ha_cluster_vip_mask }}" nic="{{ item.value }}" op monitor interval=10s
  with_dict: "{{ postgres_ha_network_rings }}"
  # pcs_resource: command=create resource_id="{{ postgres_ha_cluster_vip_res_name }}" type=ocf:heartbeat:IPaddr2
  # args:
  #   options:
  #     ip: "{{ postgres_ha_cluster_vip }}"
  #     cidr_netmask: "{{ postgres_ha_cluster_vip_mask }}"
  #   operations:
  #     - action: monitor
  #       options:
  #         interval: 10s
  when: inventory_hostname == postgres_ha_cluster_master_host   # run only on one node



