---
- name: Install php
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - php
    - libapache2-mod-php
    - php-mcrypt
    - php-mysql
    - php-cli
    - php-dev
  become: yes
