---
- debug:
    msg: "node name is {{ ansible_hostname }}"

- name: stop rabbitmq app
  shell: rabbitmqctl stop_app

- name: join rabbitmq cluster
  shell: "rabbitmqctl join_cluster {{ rabbitmq_cluster_master }}"
  register: rabbitmq_output
  ignore_errors: true

- name: ensure rabbitmq cluster member
  fail: msg="Unable to join the cluster."
  when: ("'already_member' not in rabbitmq_output.stderr") and rabbitmq_output.rc != 0

- name: start rabbitmq app
  shell: rabbitmqctl start_app

- name: clsuter status
  shell: rabbitmqctl cluster_status
