---
- name: disable ufw
  service:
    name: ufw
    state: stopped
    enabled: no
  become: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present
  become: yes

- apt_repository:
    repo: "deb https://dl.bintray.com/rabbitmq/debian $distribution main"
    state: present
  become: yes

- apt_repository:
    repo: "deb http://dl.bintray.com/rabbitmq/debian bionic erlang"
    state: present
  become: yes

- name: Install packages
  apt: name={{ item }} state=latest update_cache=yes
  become: yes
  with_items:
    - erlang-nox
    - socat
    - logrotate
    - init-system-helpers
    - adduser
    - rabbitmq-server

- name: add remote access to web console
  copy:
    src: files/rabbitmq.config
    dest: /etc/rabbitmq/rabbitmq.config
    owner: root
    group: root
    mode: 0644
  become: yes

- name: set erlang cookie
  copy:
    src: files/.erlang.cookie
    dest: "{{ rabbitmq_erlang_cookie_file }}"
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  become: yes
  when: rabbitmq_cluster

- name: start rabbitmq-server
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
  become: yes

- name: Enables the rabbitmq_management plugin
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
  become: yes
  with_items: "{{ rabbitmq_plugins }}"

- name: include vhosts.yml
  include_tasks: vhosts.yml
  become: yes

- name: include users.yml
  include_tasks: users.yml
  become: yes

- debug:
    msg: "The master node is {{ rabbitmq_cluster_master }}"
  run_once: true
  when: rabbitmq_cluster

- name: include cluster.yml
  include_tasks: cluster.yml
  become: yes
  when: rabbitmq_cluster and rabbitmq_nodename != rabbitmq_cluster_master


  