---
- name: Install package munin-node
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - munin-node 
    - munin-plugins-extra
    - python-pip
    - build-essential 
    - python-dev
  become: yes

- name: install pymongo
  pip:
    name: pymongo
  become: yes

- name: Download plugins mongodb
  git:
    repo: 'https://github.com/comerford/mongo-munin.git'
    dest: /tmp/mongo-munin
  become: yes

- name: copy mongo plugins to munin plugins directory
  shell:  cp /tmp/mongo-munin/mongo_* /usr/share/munin/plugins
  become: yes
  ignore_errors: yes

- name: chmod +x mongo plugins 
  shell:  chmod +x /usr/share/munin/plugins/mongo_*
  become: yes

- name: set env for mongo plugin
  template:
    src: templates/munin-node
    dest: /etc/munin/plugin-conf.d/munin-node
  become: yes

- name: plugin for docker
  copy:
    src: "files/{{ item }}"
    dest: "/usr/share/munin/plugins/{{ item }}"
    mode: 0755
  become: yes
  with_items:
    - docker_cpu
    - docker_memory

- name: config plugin for docker
  copy:
    src: files/docker
    dest: /etc/munin/plugin-conf.d/docker
  become: yes


- name: configure munin-node.conf
  template:
    src: templates/munin-node.conf
    dest: /etc/munin/munin-node.conf
  become: yes

- name: Install plugins munin
  shell: ln -s /usr/share/munin/plugins/{{ item }}* /etc/munin/plugins/
  with_items:
    - "{{ check_service }}" 
  become: yes
  ignore_errors: yes

- name: Restart munin-node
  service:
    name: munin-node
    state: restarted
  become: yes

# for delegate_to your PC must have access to IP to delegate
- name: Add host to munin master
  remote_user: root
  blockinfile:
    dest: /etc/munin/munin.conf
    block: |
      [{{ env }};{{ ansible_hostname }}]
        address {{ ansible_ssh_host }}
        use_node_name yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ env }}; {{ ansible_hostname }}"
    backup: yes
  become: yes
  delegate_to: "{{ ip_nagios }}"

- name: Restart apache on munin master
  remote_user: root
  service:
    name: apache2
    state: restarted
  become: yes
  delegate_to: "{{ ip_nagios }}"  

