---
- name: Install package munin-node
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - munin-node 
    - munin-plugins-extra
  become: yes

- name: configure munin-node.conf
  template:
    src: templates/munin-node.conf
    dest: /etc/munin/munin-node.conf
  become: yes

- name: Install plugins munin
  shell: ln -s /usr/share/munin/plugins/{{ item }}* /etc/munin/plugins/
  with_items:
    - "{{ check_service }}" 
  become: yes
  ignore_errors: yes

- name: Restart munin-node
  service:
    name: munin-node
    state: restarted
  become: yes

# for delegate_to your PC must have access to IP to delegate
- name: Add host to munin master
  remote_user: root
  blockinfile:
    dest: /etc/munin/munin.conf
    block: |
      [{{ env }};{{ ansible_hostname }}]
        address {{ ansible_ssh_host }}
        use_node_name yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ env }}; {{ ansible_hostname }}"
    backup: yes
  become: yes
  delegate_to: "{{ ip_nagios }}"

- name: Restart apache on munin master
  remote_user: root
  service:
    name: apache2
    state: restarted
  become: yes
  delegate_to: "{{ ip_nagios }}"  

