---
- name: Install nrpe
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - nagios-nrpe-server 
    - nagios-plugins
  become: yes

- name: Configure NRPE Client.
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    line: "allowed_hosts=127.0.0.1, {{ ip_nagios }}"
    regexp: "^allowed_hosts=127.0.0.1"
  become: yes

- name: Restart NRPE
  service:
    name: nagios-nrpe-server
    state: restarted
  become: yes
