---
- name: Install nrpe
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - nagios-nrpe-server 
    - nagios-plugins
  become: yes

- name: custom nrpe.cfg
  template:
    src: templates/nrpe.cfg
    dest: /etc/nagios/nrpe.cfg
  become: yes

- name: Restart NRPE
  service:
    name: nagios-nrpe-server
    state: restarted
  become: yes
