---
- include: full_reset.yml
  when: mgr_full_reset

- name: Install a apt mysql.deb package from the internet.
  apt:
    deb: https://repo.mysql.com//mysql-apt-config_0.8.8-1_all.deb

- name: Install mysql
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: start service mysql
  service: name={{ mysql_service }} state=started enabled=yes

- name: Create my.cnf
  template: src=../templates/my.cnf.j2 dest=/root/.my.cnf

- name: ensure anonymous users are not in the database
  mysql_user: name='' host_all=yes state=absent

- name: Remove test database
  mysql_db: name=test state=absent

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password="{{ mysql_root_db_pass }}"
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost

- name: Copy Mysql config
  copy: src=../files/mysqld.cnf dest=/etc/mysql/mysql.conf.d/mysqld.cnf mode=0644 owner=root group=root

- name: Restart service Mysql
  service:
    name: mysql
    state: restarted
  when: not mysql_group_replication_deployment

- include: mgr.yml
  when: mysql_group_replication_deployment
