---
- name: Update repositories cache
  apt:
    update_cache: yes
  become: yes

- name: Add mongo ppa key
  apt_key: >
    keyserver=hkp://keyserver.ubuntu.com:80
    id=2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    state=present
  become: yes
 
- name: Add mongo sources list
  lineinfile: >
    line="deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse"
    dest=/etc/apt/sources.list.d/mongodb-org-3.6.list
    state=present
    create=yes
  become: yes

- name: Install mongo
  apt: name=mongodb-org state=latest update_cache=yes
  become: yes

- name: update config file mongod.conf
  template:
    src: templates/mongod.conf
    dest: /etc/mongod.conf
  become: yes
  tags:
    - admin 

- name: start mongod service
  service:
    name: mongod
    state: started
    enabled: yes
  become: yes

- name: copy file admin.js
  template:
    src: templates/admin.js.j2
    dest: /tmp/admin.js
  become: yes

 
- name: config admin user
  command: mongo localhost:27017 /tmp/admin.js
  become: yes

- name: test access with admin user
  command: mongo -u{{ mongo_user }} -p{{ mongo_pwd }} --authenticationDatabase admin
  register: mongo_auth

- fail:
    msg: "PB authentication"
  when: mongo_auth.failed

- name: add authorization enabled
  blockinfile:
    path: /etc/mongod.conf
    block: |2
      security:
        authorization: enabled
    marker: "# {mark} ANSIBLE MANAGED BLOCK SECURITY"
  become: yes

- name: logrotate mongod log file
  copy:
    src: files/mongod
    dest: /etc/logrotate.d/mongod
  become: yes

- name: add replica set name 
  blockinfile:
    path: /etc/mongod.conf
    block: |2
      replication:
        replSetName: rs0
    marker: "# {mark} ANSIBLE MANAGED BLOCK REPLICA SET"
  become: yes
  when: mongo_replicaset_setup

- name: Create mongodb home directory
  file:
    state: directory
    path: "{{ mongo_keyfile_dir }}"
    owner: mongodb
    group: mongodb
    mode: 0755
  become: yes
  when: mongo_replicaset_setup

- name: Copy key to both master and slaves
  copy:
    src: files/mongodb-key
    dest: "{{ mongo_keyfile_dir }}/mongodb-key"
    owner: mongodb
    group: mongodb
    mode: 0400
  become: yes
  when: mongo_replicaset_setup 

- name: add keyfile authorization 
  blockinfile:
    path: /etc/mongod.conf
    block: |2
      security:
        authorization: enabled
        keyFile: {{ mongo_keyfile_dir }}/mongodb-key
    marker: "# {mark} ANSIBLE MANAGED BLOCK SECURITY"
  become: yes
  when: mongo_replicaset_setup 

- name: restart mongod 
  service:
    name: mongod
    state: restarted
  become: yes

- name: copy file replica.js
  template:
    src: templates/replica.js.j2
    dest: /tmp/replica.js
  become: yes
  when: (node_server_id == 1) and (mongo_replicaset_setup)

- name: sleep for 30 seconds and continue with play
  wait_for: timeout=30
  when: (node_server_id == 1) and (mongo_replicaset_setup)


- name: config replica set
  command: mongo localhost:27017/admin -u{{ mongo_user }} -p{{ mongo_pwd }} --authenticationDatabase admin /tmp/replica.js
  become: yes
  when: (node_server_id == 1) and (mongo_replicaset_setup)
  tags:
    - rep

