---
- name: Install ufw
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - ufw
  become: yes

- name: Set ipv6 yes /etc/default/ufw
  lineinfile:
    dest: /etc/default/ufw
    regexp: '^IPV6='
    line: 'IPV6=yes'
  become: yes

- name: reset firewall
  ufw:
    state: reset
  become: true
  tags:
    - reset_rules

- name: allow ssh access
  ufw:
    rule: allow
    port: 22
  become: yes
  tags:
    - reset_rules

# Allow all access from RFC1918 networks to this host:
- name: allow ip from inventory
  ufw:
    rule: allow
    src: '{{ hostvars[item].ansible_ssh_host }}'
  become: yes
  with_items:
    - "{{ groups['all'] }}"
  tags:
    - reset_rules
    - add_rules
    

- name: allow localhost
  ufw:
    rule: allow
    src: 127.0.0.1
  become: yes
  tags:
    - reset_rules

- name: Configuring port/protocol/network rules
  ufw:
    delete: "{{ item.delete | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    rule: "{{ item.rule | default('allow') }}"
    state: "{{ item.state | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
  become: yes
  with_items: "{{ ufw_rules }}"
  when : ufw_rules is defined
  tags:
    - add_rules
    - reset_rules

- name: start firewall
  ufw:
    state: enabled
    logging: on
  become: true
  tags:
    - add_rules
    - reset_rules