- name: install docker
  hosts: nagios
  vars:
    - apache2_for_php: true
  roles:
    - nagios
  become: true

  #tasks:
  #  - name: Install zenity
  #    shell:   echo "{{ansible_fqdn}} done" >> /tmp/list
  #  - name: Tell Master
  #    remote_user: vagrant
  #    shell:  echo "{{ansible_fqdn}} done" >> /tmp/list
  #    delegate_to: 192.168.100.12

- name: install client
  hosts: all:!nagios
  roles:
    - nrpe
  become: true
