# - name: install graphite
#   hosts: mysql
#   vars:
#     - mysql_group_replication_deployment: false
#     - mgr_full_reset: false
#     - apache2_for_php: false
#   roles:
#     - graphite
#     - grafana
#   become: true

- name: install graphite
  hosts: proxysql
  vars:
    - mysql_group_replication_deployment: false
    - mgr_full_reset: false
    - collectd_enable_mysql: true
  roles:
    - mysql
    - collectd
  become: true

# - name: install proxysql
#   hosts: proxysql
#   vars:
#     - apache2_for_php: false
#   roles:
#     - basics
#     - proxysql
#   become: true

  #tasks:
  #  - name: Install zenity
  #    shell:   echo "{{ansible_fqdn}} done" >> /tmp/list
  #  - name: Tell Master
  #    remote_user: vagrant
  #    shell:  echo "{{ansible_fqdn}} done" >> /tmp/list
  #    delegate_to: 192.168.100.12

# - name: install client
#   hosts: all:!nagios
#   roles:
#     - nrpe
#     - munin-node
#   become: true

# - name: For getting cluster info
#   hosts: lb
#   vars:
#     - haproxy_http: true
#   roles:
#     - ssh
#     - users_mgmt
#     - haproxy
#     - keepalived
#   become: true

  
# - name: install munin-node
#   hosts: web
#   vars:
#     - apache2_for_php: true
#   roles:
#     - ssh
#     - users_mgmt
#     - apache2
#     - php
#   become: true

# - name: install munin-node
#   hosts: web
#   vars:
#     - apache2_for_php: false
#   roles:
#     - ssh
#     - users_mgmt
#     - apache2
#   become: true
