# - name: install docker
#   hosts: nagios
#   vars:
#     - apache2_for_php: false
#   roles:
#     - ssh
#     - users_mgmt
#     - munin
#   become: true

  #tasks:
  #  - name: Install zenity
  #    shell:   echo "{{ansible_fqdn}} done" >> /tmp/list
  #  - name: Tell Master
  #    remote_user: vagrant
  #    shell:  echo "{{ansible_fqdn}} done" >> /tmp/list
  #    delegate_to: 192.168.100.12

# - name: install client
#   hosts: all:!nagios
#   roles:
#     - nrpe
#     - munin-node
#   become: true

- name: install munin-node
  hosts: mongo
  vars:
    - mongo_replicaset_setup: false
  roles:
    - ssh
    - users_mgmt
    - mongo
    - munin-node
  become: true
