---
- name: Install postfix
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - mailutils
    - bsd-mailx
  become: yes

- name: Add mailname.
  template:
    src: templates/mailname
    dest: /etc/mailname
  become: yes

- name: Update Postfix configuration.
  template:
    src: templates/main.cf
    dest: /etc/postfix/main.cf
  become: yes
  tags:
    - main
  
- name: Update aliases file
  template:
    src: aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Run newaliases
  shell: newaliases
  become: yes


- name: Restart postfix
  service:
    name: postfix
    state: restarted
  become: yes
