---
- name: Install postfix
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - mailutils
    - bsd-mailx
  become: yes

- name: Update Postfix configuration.
  lineinfile:
    dest: /etc/postfix/main.cf
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }} ="
  with_items:
    - "{{ postfix_vars }}"
  become: yes

- name: Update aliases file
  template:
    src: aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Run newaliases
  shell: newaliases
  become: yes


- name: Restart postfix
  service:
    name: postfix
    state: restarted
  become: yes
